input:
  directory: C:\Users\tminh\Downloads\test_video_filter

curation_parameters:
  model: RetinaFace
  min_face_size: 100

  exposure: correct
  emotion: happy
  dummy: very

output:
  directory: results
